### PR TITLE
PSTwitter Remastered v2.0

### PR DESCRIPTION
**Pull request by mkellerman**
How do i upload my latest version?

### CODE REVIEW

**Comment by CollinChaffin** [comment]
I apologize admittedly I have had zero time lately to commit to this and need to catch up.  I will start looking through your code changes/additions this weekend and then we can get them merged back in!

**Comment by mkellerman** [comment]
I’m not 100% sure i got this GitHub thing down pack..

can i simply send you the modified file? I dont know how to upload my latest copy.. it’s VERY different than your version.. but i think it’s for the better.

Been using this code on production in the last year, and it’s been a beauty!

**Comment by CollinChaffin** [comment]
Yes on this thread at the bottom do you see where it allows you to attach a file?  Go ahead and attach it for now I do see a pull request let me review it all and then I can try to commmit your changes as well!

**Comment by mkellerman** [comment]
can you see my Remastered 2.0 fork?

**Comment by mkellerman** [comment]
Did you get a change to peek at it? :/

**Comment by CollinChaffin** [comment]
Hey Marc,

Can you hit me up on Twitter please?  I want to touch base with you regarding your code additions to my PSTwitter.

Thanks!

Collin

**Comment by CollinChaffin** [comment]
Hey Marc,

Thanks for the info and chat today.  I am reviewing this old pull code and comparing to other updated functions you sent me.  I think I agree with you and may just incorporate by hand a merge of your functions and just be sure to add/update each function comments to call out credit to you.

Thanks again for all the hard work you put in to improve this.  Look for an updated build here soon!  I will close this pull/issue once the next build goes live!

Collin

**Pull request closed without merging**
